---
title: "Figure X"
format: html
editor: visual
---

```{r setup}

# Load packages
library(PhaseTypeR)
library(tidyverse)
library(ggthemes)

```

```{r}

mean_random_mat <- function(n) {
  mat <- matrix(sample(0:10, (n+1)*(n+1), replace = T), nrow = n+1)
  diag(mat) <- rep(0, n+1)
  diag(mat) <- -rowSums(mat)
  mat <- mat[1:n,1:n]
  init <- sample(0:10, n+1, replace = T)
  init <- init/sum(init)
  init <- init[1:n]
  start_time <- Sys.time()
  mean(PH(mat, init))
  end_time <- Sys.time()
  as.numeric(end_time - start_time)
}

```

```{r}

set.seed(10)
n_rep <- 1:3
n_states_tot <- c()
times <- c()
for (i in n_rep) {
  print(i)
  n_states <- seq(2, 2000, 50)
  n_states_tot <- c(n_states_tot, n_states)
  times <- c(times, unlist(lapply(n_states, function(i) try(mean_random_mat(i), TRUE))))
}

```

```{r}

tab <- tibble(n_states_2 = n_states_tot, time = as.numeric(times)) |> 
  group_by(n_states_2) |> 
  mutate(time = mean(time, na.rm = T)) |> 
  ungroup() |> 
  drop_na()


tab |> 
  ggplot(aes(n_states_2, time)) +
  geom_point() 
  

```

```{r}

var_random_mat <- function(n) {
  mat <- matrix(sample(0:10, (n+1)*(n+1), replace = T), nrow = n+1)
  diag(mat) <- rep(0, n+1)
  diag(mat) <- -rowSums(mat)
  mat <- mat[1:n,1:n]
  init <- sample(0:10, n+1, replace = T)
  init <- init/sum(init)
  init <- init[1:n]
  start_time <- Sys.time()
  var(PH(mat, init))
  end_time <- Sys.time()
  as.numeric(end_time - start_time)
}

```

```{r}

set.seed(10)
n_rep <- 1:3
n_states_tot <- c()
times <- c()
for (i in n_rep) {
  print(i)
  n_states <- seq(2, 2000, 50)
  n_states_tot <- c(n_states_tot, n_states)
  times <- c(times, unlist(lapply(n_states, function(i) try(var_random_mat(i), TRUE))))
}

```

```{r}

tab <- tibble(n_states_2 = n_states_tot, time = as.numeric(times)) |> 
  group_by(n_states_2) |> 
  mutate(time = median(time, na.rm = T)) |> 
  ungroup() |> 
  drop_na()


tab |> 
  ggplot(aes(n_states_2, time)) +
  geom_point() 
  

```


